'use client';

import { Activity, AlertTriangle, BarChart3, BookOpenCheck, CheckCircle2, RefreshCw, Target, TrendingUp, Users } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useLanguage } from '../../../components/LanguageProvider';
import { api } from '../../../lib/api';

const EMPTY = { students: 0, activeStudents: 0, attempts: 0, averageScore: 0, weeklyAttempts: 0, weeklyActiveStudents: 0, publishRate: 0, dailyActivity: [], scoreDistribution: [], chapterPerformance: [], recentAttempts: [] };
const text = (language, bn, en) => language === 'bn' ? bn : en;
const number = (value, language) => Number(value || 0).toLocaleString(language === 'bn' ? 'bn-BD' : 'en-US');
const localName = (value, language) => value?.[language] || (language === 'bn' ? value?.bn || value?.en : value?.en || value?.bn) || text(language, 'নাম পাওয়া যায়নি', 'Name unavailable');
const formatDate = (value, language, options = { weekday: 'short' }) => new Intl.DateTimeFormat(language === 'bn' ? 'bn-BD' : 'en-GB', options).format(new Date(value));

export default function TeacherAnalytics() {
  const { language } = useLanguage();
  const [data, setData] = useState(EMPTY), [loading, setLoading] = useState(true), [refreshing, setRefreshing] = useState(false), [error, setError] = useState('');
  const load = useCallback(async (quiet = false) => { quiet ? setRefreshing(true) : setLoading(true); try { const result = await api('/analytics/teacher'); setData({ ...EMPTY, ...(result.data || {}) }); setError(''); } catch (requestError) { setError(requestError.message || text(language, 'বিশ্লেষণের তথ্য লোড করা যায়নি।', 'Analytics data could not be loaded.')); } finally { setLoading(false); setRefreshing(false); } }, [language]);
  useEffect(() => { load(); }, [load]);
  const maxDaily = Math.max(...data.dailyActivity.map((item) => item.attempts), 1);
  const distributionTotal = Math.max(data.scoreDistribution.reduce((sum, item) => sum + item.count, 0), 1);
  const engagement = data.students ? Math.round((data.weeklyActiveStudents / data.students) * 100) : 0;
  const insights = useMemo(() => {
    const weak = data.chapterPerformance[0];
    return [
      { tone: engagement >= 60 ? 'success' : 'warning', title: text(language, 'সাপ্তাহিক অংশগ্রহণ', 'Weekly engagement'), value: `${number(engagement, language)}%`, detail: text(language, `${number(data.weeklyActiveStudents, language)} জন শিক্ষার্থী গত ৭ দিনে সক্রিয় ছিল।`, `${number(data.weeklyActiveStudents, language)} students were active in the last 7 days.`) },
      { tone: weak?.accuracy < 60 ? 'error' : 'success', title: text(language, 'অগ্রাধিকার অধ্যায়', 'Priority chapter'), value: weak ? localName(weak.name, language) : '—', detail: weak ? text(language, `সঠিকতার হার ${number(weak.accuracy, language)}%—পরবর্তী পাঠে পুনরালোচনা করুন।`, `${number(weak.accuracy, language)}% accuracy—consider revisiting it in the next lesson.`) : text(language, 'অন্তর্দৃষ্টির জন্য আরও টেস্ট প্রয়োজন।', 'More tests are needed for an insight.') },
      { tone: data.publishRate >= 80 ? 'success' : 'warning', title: text(language, 'প্রশ্নভাণ্ডারের প্রস্তুতি', 'Question-bank readiness'), value: `${number(data.publishRate, language)}%`, detail: text(language, 'মোট প্রশ্নের মধ্যে প্রকাশিত প্রশ্নের অনুপাত।', 'Share of the question bank currently published.') },
    ];
  }, [data, engagement, language]);

  return <main className="mx-auto max-w-7xl p-5 md:p-10">
    <header className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-[10px] font-bold tracking-[.18em] text-base-content/50">{text(language, 'শিক্ষা বিশ্লেষণ', 'LEARNING ANALYTICS')}</p><h1 className="mt-2 font-display text-4xl font-bold">{text(language, 'ক্লাসের পারফরম্যান্স', 'Class performance')}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-base-content/60">{text(language, 'অংশগ্রহণ, শেখার ফলাফল এবং কনটেন্টের প্রস্তুতি পর্যবেক্ষণ করে পরবর্তী পদক্ষেপ নির্ধারণ করুন।', 'Monitor engagement, learning outcomes, and content readiness to guide your next action.')}</p></div><button className="btn btn-outline" disabled={refreshing} onClick={() => load(true)}><RefreshCw size={17} className={refreshing ? 'animate-spin' : ''}/>{text(language, 'তথ্য হালনাগাদ', 'Refresh data')}</button></header>
    {error && <div className="alert alert-error mt-6"><AlertTriangle size={19}/><span>{error}</span></div>}
    {loading ? <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[1,2,3,4].map((item) => <div className="skeleton h-32" key={item}/>)}</div> : <>
      <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
        [text(language, 'মোট শিক্ষার্থী', 'Total students'), data.students, Users, 'text-primary', text(language, `${number(data.activeStudents, language)}টি সক্রিয় অ্যাকাউন্ট`, `${number(data.activeStudents, language)} active accounts`)],
        [text(language, 'সাপ্তাহিক টেস্ট', 'Weekly tests'), data.weeklyAttempts, Activity, 'text-accent', text(language, 'গত ৭ দিনে সম্পন্ন', 'Completed in the last 7 days')],
        [text(language, 'গড় স্কোর', 'Average score'), `${number(data.averageScore, language)}%`, Target, 'text-warning', text(language, `${number(data.attempts, language)}টি টেস্টের হিসাবে`, `Across ${number(data.attempts, language)} tests`)],
        [text(language, 'প্রকাশের হার', 'Publish rate'), `${number(data.publishRate, language)}%`, BookOpenCheck, 'text-success', text(language, 'প্রশ্নভাণ্ডারের প্রস্তুতি', 'Question-bank readiness')],
      ].map(([label, value, Icon, tone, detail]) => <article className="rounded-box border border-base-300 bg-base-100 p-5 shadow-sm" key={label}><div className="flex justify-between"><p className="text-xs text-base-content/55">{label}</p><Icon size={21} className={tone}/></div><b className="mt-3 block font-display text-3xl">{typeof value === 'number' ? number(value, language) : value}</b><p className="mt-1 text-xs text-base-content/45">{detail}</p></article>)}</section>
      <div className="mt-6 grid gap-5 xl:grid-cols-[1.35fr_1fr]">
        <section className="rounded-box border border-base-300 bg-base-100 p-5 shadow-sm md:p-6"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold tracking-widest text-base-content/45">{text(language, '৭ দিনের প্রবণতা', '7-DAY TREND')}</p><h2 className="font-display text-2xl font-bold">{text(language, 'টেস্ট কার্যক্রম', 'Test activity')}</h2></div><TrendingUp className="text-primary"/></div><div className="mt-8 flex h-56 items-end gap-3 border-b border-base-300 px-2">{data.dailyActivity.map((item) => <div className="flex h-full flex-1 flex-col justify-end text-center" key={item.date}><span className="mb-2 text-xs font-bold">{number(item.attempts, language)}</span><div className="mx-auto w-full max-w-14 rounded-t bg-primary/80 transition-all" style={{ height: `${Math.max((item.attempts / maxDaily) * 80, item.attempts ? 8 : 2)}%` }} title={`${item.attempts} tests`}/><span className="mt-2 text-[11px] text-base-content/50">{formatDate(item.date, language)}</span></div>)}</div><p className="mt-5 text-xs text-base-content/50">{text(language, 'দৈনিক সম্পন্ন টেস্টের সংখ্যা। কম কার্যক্রমের দিনগুলো পাঠ পরিকল্পনার সময় বিবেচনা করুন।', 'Daily completed tests. Consider low-activity days when planning learner outreach.')}</p></section>
        <section className="rounded-box border border-base-300 bg-base-100 p-5 shadow-sm md:p-6"><p className="text-[10px] font-bold tracking-widest text-base-content/45">{text(language, 'ফলাফলের বিস্তার', 'SCORE DISTRIBUTION')}</p><h2 className="font-display text-2xl font-bold">{text(language, 'শিক্ষার্থীদের ফলাফল', 'Learner outcomes')}</h2><div className="mt-7 space-y-6">{data.scoreDistribution.map((item) => { const config = { excellent: [text(language, 'চমৎকার (৮০–১০০%)', 'Excellent (80–100%)'), 'progress-success'], developing: [text(language, 'উন্নয়নশীল (৬০–৭৯%)', 'Developing (60–79%)'), 'progress-warning'], needsSupport: [text(language, 'সহায়তা প্রয়োজন (০–৫৯%)', 'Needs support (0–59%)'), 'progress-error'] }[item.key]; return <div key={item.key}><div className="mb-2 flex justify-between text-sm"><span>{config[0]}</span><b>{number(item.count, language)}</b></div><progress className={`progress w-full ${config[1]}`} value={item.count} max={distributionTotal}/></div>; })}</div></section>
      </div>
      <div className="mt-6 grid gap-5 xl:grid-cols-[1fr_1.2fr]">
        <section className="rounded-box border border-base-300 bg-base-100 p-5 shadow-sm md:p-6"><p className="text-[10px] font-bold tracking-widest text-base-content/45">{text(language, 'করণীয়', 'ACTIONABLE INSIGHTS')}</p><h2 className="font-display text-2xl font-bold">{text(language, 'পরবর্তী পদক্ষেপ', 'Recommended focus')}</h2><div className="mt-5 space-y-3">{insights.map((item) => <article className={`rounded-box border p-4 ${item.tone === 'error' ? 'border-error/25 bg-error/5' : item.tone === 'warning' ? 'border-warning/25 bg-warning/5' : 'border-success/25 bg-success/5'}`} key={item.title}><div className="flex items-start gap-3"><CheckCircle2 size={19} className={item.tone === 'error' ? 'text-error' : item.tone === 'warning' ? 'text-warning' : 'text-success'}/><div className="min-w-0"><p className="text-xs font-bold text-base-content/55">{item.title}</p><b className="mt-1 block truncate">{item.value}</b><p className="mt-1 text-xs leading-5 text-base-content/55">{item.detail}</p></div></div></article>)}</div></section>
        <section className="rounded-box border border-base-300 bg-base-100 p-5 shadow-sm md:p-6"><div className="flex justify-between"><div><p className="text-[10px] font-bold tracking-widest text-base-content/45">{text(language, 'অধ্যায় বিশ্লেষণ', 'CHAPTER ANALYSIS')}</p><h2 className="font-display text-2xl font-bold">{text(language, 'সহায়তা প্রয়োজন এমন অধ্যায়', 'Chapters needing support')}</h2></div><BarChart3 className="text-primary"/></div>{data.chapterPerformance.length ? <div className="mt-6 space-y-5">{data.chapterPerformance.map((chapter) => <div key={chapter.chapterId}><div className="mb-2 flex justify-between gap-3 text-sm"><span className="truncate font-semibold">{localName(chapter.name, language)}</span><b className={chapter.accuracy < 60 ? 'text-error' : 'text-primary'}>{number(chapter.accuracy, language)}%</b></div><progress className={`progress w-full ${chapter.accuracy < 60 ? 'progress-error' : 'progress-primary'}`} value={chapter.accuracy} max="100"/><p className="mt-1 text-[10px] text-base-content/40">{text(language, `${number(chapter.attempted, language)}টি উত্তর বিশ্লেষণ করা হয়েছে`, `${number(chapter.attempted, language)} answers analyzed`)}</p></div>)}</div> : <p className="py-12 text-center text-sm text-base-content/50">{text(language, 'অধ্যায় বিশ্লেষণের জন্য আরও টেস্ট প্রয়োজন।', 'More tests are needed for chapter analysis.')}</p>}</section>
      </div>
    </>}
  </main>;
}
