'use client';

import { ChevronDown, ChevronRight, ChevronsDown, ChevronsUp, MoveDown, MoveUp, Pencil, Plus, Trash2, X } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { api } from '../lib/api';
import { useLanguage } from './LanguageProvider';

const text = (language, bn, en) => language === 'bn' ? bn : en;
const number = (value, language) => Number(value || 0).toLocaleString(language === 'bn' ? 'bn-BD' : 'en-US');
const nameFor = (item, language) => item?.name?.[language] || (language === 'bn' ? item?.name?.bn || item?.name?.en : item?.name?.en || item?.name?.bn) || '—';

export default function SyllabusManager() {
  const { language } = useLanguage();
  const [tree, setTree] = useState([]), [expanded, setExpanded] = useState({});
  const [form, setForm] = useState({ type: 'chapter', chapterId: '', topicId: '', bn: '', en: '' });
  const [editing, setEditing] = useState(null), [feedback, setFeedback] = useState({ type: '', message: '' });
  const [loading, setLoading] = useState(true), [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const result = await api('/syllabus/tree'); setTree(result.data || []); } catch (error) { setFeedback({ type: 'error', message: error.message }); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const totals = useMemo(() => ({ chapters: tree.length, topics: tree.reduce((sum, chapter) => sum + chapter.topics.length, 0), subtopics: tree.reduce((sum, chapter) => sum + chapter.topics.reduce((count, topic) => count + topic.subtopics.length, 0), 0), questions: tree.reduce((sum, chapter) => sum + Number(chapter.questionCount || 0), 0) }), [tree]);
  const topics = tree.find((chapter) => chapter._id === form.chapterId)?.topics || [];
  const allIds = tree.flatMap((chapter) => [chapter._id, ...chapter.topics.map((topic) => topic._id)]);
  const create = async (event) => { event.preventDefault(); setSaving(true); const siblings = form.type === 'chapter' ? tree : form.type === 'topic' ? topics : topics.find((topic) => topic._id === form.topicId)?.subtopics || []; const body = { name: { bn: form.bn.trim(), en: form.en.trim() }, order: siblings.length + 1 }; if (form.type === 'chapter') body.title = form.en.trim(); if (form.type !== 'chapter') body.chapterId = form.chapterId; if (form.type === 'subtopic') body.topicId = form.topicId; try { await api(`/${form.type}s`, { method: 'POST', body: JSON.stringify(body) }); setForm((current) => ({ ...current, bn: '', en: '' })); setFeedback({ type: 'success', message: text(language, 'নতুন অংশ যোগ করা হয়েছে।', 'Syllabus item added.') }); await load(); } catch (error) { setFeedback({ type: 'error', message: error.message }); } finally { setSaving(false); } };
  const saveEdit = async (event) => { event.preventDefault(); setSaving(true); const body = { name: { bn: editing.bn.trim(), en: editing.en.trim() } }; if (editing.type === 'chapter') body.title = editing.en.trim(); try { await api(`/${editing.type}s/${editing.item._id}`, { method: 'PATCH', body: JSON.stringify(body) }); setEditing(null); setFeedback({ type: 'success', message: text(language, 'পরিবর্তন সংরক্ষণ করা হয়েছে।', 'Changes saved.') }); await load(); } catch (error) { setFeedback({ type: 'error', message: error.message }); } finally { setSaving(false); } };
  const remove = async (type, item) => { if (!window.confirm(text(language, `“${nameFor(item, language)}” সরাবেন? ব্যবহৃত হলে এটি নিরাপদে আর্কাইভ করা হবে।`, `Remove “${nameFor(item, language)}”? Referenced content will be archived safely.`))) return; try { const result = await api(`/${type}s/${item._id}`, { method: 'DELETE' }); setFeedback({ type: 'success', message: result?.message || text(language, 'অংশটি সরানো হয়েছে।', 'Item removed.') }); await load(); } catch (error) { setFeedback({ type: 'error', message: error.message }); } };
  const reorder = async (type, siblings, index, direction) => { const next = [...siblings], target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; try { await api(`/${type}s/reorder`, { method: 'PATCH', body: JSON.stringify({ items: next.map((item, order) => ({ id: item._id, order: order + 1 })) }) }); await load(); } catch (error) { setFeedback({ type: 'error', message: error.message }); } };
  const Controls = ({ type, item, siblings, index }) => <span className="flex shrink-0 gap-1"><button type="button" disabled={!index} onClick={() => reorder(type, siblings, index, -1)} className="btn btn-ghost btn-xs" title={text(language, 'উপরে নিন', 'Move up')}><MoveUp size={13}/></button><button type="button" disabled={index === siblings.length - 1} onClick={() => reorder(type, siblings, index, 1)} className="btn btn-ghost btn-xs" title={text(language, 'নিচে নিন', 'Move down')}><MoveDown size={13}/></button><button type="button" onClick={() => setEditing({ type, item, bn: item.name.bn, en: item.name.en })} className="btn btn-ghost btn-xs" aria-label={text(language, 'সম্পাদনা', 'Edit')}><Pencil size={13}/></button><button type="button" onClick={() => remove(type, item)} className="btn btn-ghost btn-xs text-error" aria-label={text(language, 'আর্কাইভ বা মুছুন', 'Archive or delete')}><Trash2 size={13}/></button></span>;

  return <main className="mx-auto max-w-6xl p-5 md:p-10">
    <header className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-[10px] font-bold tracking-[.18em] text-base-content/50">{text(language, 'একাডেমিক কাঠামো', 'ACADEMIC STRUCTURE')}</p><h1 className="mt-2 font-display text-4xl font-bold">{text(language, 'সিলেবাস পরিচালনা', 'Syllabus management')}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-base-content/60">{text(language, 'অধ্যায় → টপিক → সাবটপিক কাঠামো সাজান। প্রশ্নে ব্যবহৃত অংশ নিরাপদে আর্কাইভ করা হয়।', 'Organize the Chapter → Topic → Subtopic hierarchy. Referenced items are archived safely.')}</p></div><div className="flex gap-2"><button className="btn btn-outline btn-sm" onClick={() => setExpanded(Object.fromEntries(allIds.map((id) => [id, true])))}><ChevronsDown size={15}/>{text(language, 'সব খুলুন', 'Expand all')}</button><button className="btn btn-ghost btn-sm" onClick={() => setExpanded({})}><ChevronsUp size={15}/>{text(language, 'সব বন্ধ করুন', 'Collapse all')}</button></div></header>
    <section className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[text(language, 'অধ্যায়', 'Chapters'), totals.chapters], [text(language, 'টপিক', 'Topics'), totals.topics], [text(language, 'সাবটপিক', 'Subtopics'), totals.subtopics], [text(language, 'প্রকাশিত প্রশ্ন', 'Published questions'), totals.questions]].map(([label, value]) => <article className="rounded-box border border-base-300 bg-base-100 p-4 shadow-sm" key={label}><p className="text-xs text-base-content/55">{label}</p><b className="mt-2 block font-display text-3xl">{number(value, language)}</b></article>)}</section>
    <form onSubmit={create} className="mt-6 rounded-box border border-base-300 bg-base-100 p-5 shadow-sm"><h2 className="font-display text-xl font-bold">{text(language, 'নতুন অংশ যোগ করুন', 'Add syllabus item')}</h2><p className="mb-4 text-xs text-base-content/50">{text(language, 'বাংলা ও ইংরেজি—দুই ভাষার নামই দিন।', 'Provide names in both Bangla and English.')}</p><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><select value={form.type} onChange={(event) => setForm({ type: event.target.value, chapterId: '', topicId: '', bn: '', en: '' })} className="select select-bordered"><option value="chapter">{text(language, 'অধ্যায়', 'Chapter')}</option><option value="topic">{text(language, 'টপিক', 'Topic')}</option><option value="subtopic">{text(language, 'সাবটপিক', 'Subtopic')}</option></select>{form.type !== 'chapter' && <select required value={form.chapterId} onChange={(event) => setForm((current) => ({ ...current, chapterId: event.target.value, topicId: '' }))} className="select select-bordered"><option value="">{text(language, 'অধ্যায় নির্বাচন করুন', 'Select chapter')}</option>{tree.map((chapter) => <option key={chapter._id} value={chapter._id}>{nameFor(chapter, language)}</option>)}</select>}{form.type === 'subtopic' && <select required value={form.topicId} onChange={(event) => setForm((current) => ({ ...current, topicId: event.target.value }))} className="select select-bordered"><option value="">{text(language, 'টপিক নির্বাচন করুন', 'Select topic')}</option>{topics.map((topic) => <option key={topic._id} value={topic._id}>{nameFor(topic, language)}</option>)}</select>}<input required value={form.bn} onChange={(event) => setForm((current) => ({ ...current, bn: event.target.value }))} placeholder={text(language, 'বাংলা নাম', 'Bangla name')} className="input input-bordered"/><input required value={form.en} onChange={(event) => setForm((current) => ({ ...current, en: event.target.value }))} placeholder={text(language, 'ইংরেজি নাম', 'English name')} className="input input-bordered"/><button disabled={saving} className="btn btn-primary"><Plus size={15}/>{text(language, 'যোগ করুন', 'Add')}</button></div></form>
    {feedback.message && <div className={`alert mt-4 ${feedback.type === 'error' ? 'alert-error' : 'alert-success'}`}><span>{feedback.message}</span><button className="btn btn-circle btn-ghost btn-xs" onClick={() => setFeedback({ type: '', message: '' })}><X size={14}/></button></div>}
    <section className="mt-6 overflow-hidden rounded-box border border-base-300 bg-base-100 shadow-sm"><div className="border-b border-base-300 p-5"><h2 className="font-display text-xl font-bold">{text(language, 'সিলেবাসের বিন্যাস', 'Syllabus hierarchy')}</h2></div>{loading ? <div className="space-y-3 p-5">{[1,2,3].map((item) => <div className="skeleton h-14" key={item}/>)}</div> : tree.length ? tree.map((chapter, ci) => <div key={chapter._id} className="border-b border-base-300 last:border-0"><div className="flex items-center gap-2 p-4 hover:bg-base-200/50"><button onClick={() => setExpanded((current) => ({ ...current, [chapter._id]: !current[chapter._id] }))} className="btn btn-circle btn-ghost btn-xs">{expanded[chapter._id] ? <ChevronDown size={17}/> : <ChevronRight size={17}/>}</button><b className="min-w-0 flex-1 truncate">{number(ci + 1, language)}. {nameFor(chapter, language)}</b><span className="badge badge-outline badge-sm">{number(chapter.questionCount, language)} {text(language, 'প্রশ্ন', 'questions')}</span><Controls type="chapter" item={chapter} siblings={tree} index={ci}/></div>{expanded[chapter._id] && <div className="ml-6 border-l border-primary/30 pl-3 md:ml-10">{chapter.topics.length ? chapter.topics.map((topic, ti) => <div key={topic._id}><div className="flex items-center gap-2 border-t border-base-200 p-3"><button onClick={() => setExpanded((current) => ({ ...current, [topic._id]: !current[topic._id] }))} className="btn btn-circle btn-ghost btn-xs">{expanded[topic._id] ? <ChevronDown size={15}/> : <ChevronRight size={15}/>}</button><span className="min-w-0 flex-1 truncate font-medium">{number(ci + 1, language)}.{number(ti + 1, language)} {nameFor(topic, language)}</span><span className="badge badge-ghost badge-sm">{number(topic.questionCount, language)}</span><Controls type="topic" item={topic} siblings={chapter.topics} index={ti}/></div>{expanded[topic._id] && <div className="ml-7 mb-2 border-l border-base-300 pl-3">{topic.subtopics.length ? topic.subtopics.map((subtopic, si) => <div className="flex items-center gap-2 p-2 text-sm" key={subtopic._id}><span className="min-w-0 flex-1 truncate">{number(ci + 1, language)}.{number(ti + 1, language)}.{number(si + 1, language)} {nameFor(subtopic, language)}</span><span className="badge badge-ghost badge-xs">{number(subtopic.questionCount, language)}</span><Controls type="subtopic" item={subtopic} siblings={topic.subtopics} index={si}/></div>) : <p className="p-3 text-xs text-base-content/45">{text(language, 'কোনো সাবটপিক নেই।', 'No subtopics.')}</p>}</div>}</div>) : <p className="p-5 text-sm text-base-content/45">{text(language, 'এই অধ্যায়ে কোনো টপিক নেই।', 'No topics in this chapter.')}</p>}</div>}</div>) : <div className="p-12 text-center text-sm text-base-content/55">{text(language, 'সিলেবাসে এখনো কোনো অধ্যায় নেই।', 'No chapters added yet.')}</div>}</section>
    {editing && <div className="modal modal-open" role="dialog" aria-modal="true"><form onSubmit={saveEdit} className="modal-box"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-primary">{text(language, 'সিলেবাস সম্পাদনা', 'EDIT SYLLABUS')}</p><h2 className="mt-1 font-display text-2xl font-bold">{nameFor(editing.item, language)}</h2></div><button type="button" className="btn btn-circle btn-ghost btn-sm" onClick={() => setEditing(null)}><X size={18}/></button></div><label className="form-control mt-5"><span className="label-text font-semibold">{text(language, 'বাংলা নাম', 'Bangla name')}</span><input required className="input input-bordered mt-1" value={editing.bn} onChange={(event) => setEditing((current) => ({ ...current, bn: event.target.value }))}/></label><label className="form-control mt-4"><span className="label-text font-semibold">{text(language, 'ইংরেজি নাম', 'English name')}</span><input required className="input input-bordered mt-1" value={editing.en} onChange={(event) => setEditing((current) => ({ ...current, en: event.target.value }))}/></label><div className="modal-action"><button type="button" className="btn btn-ghost" onClick={() => setEditing(null)}>{text(language, 'বাতিল', 'Cancel')}</button><button disabled={saving} className="btn btn-primary">{text(language, 'পরিবর্তন সংরক্ষণ', 'Save changes')}</button></div></form><button className="modal-backdrop" onClick={() => setEditing(null)} aria-label={text(language, 'বন্ধ করুন', 'Close')}/></div>}
  </main>;
}
